### ISSUE TITLE
Indicator: T1 Western Line not supporting trains beyond Chatswood

### ISSUE THREAD

**Issue by MLVDau** [jaboles/DVA5#1]
Currently it appears as though trains bound for Hornsby (via Macquarie University) show as Chatswood trains.

I note that when the Western Line is selected, no stations past Chatswood can be selected
![screenshot 2017-02-10 23 23 56](https://cloud.githubusercontent.com/assets/25685344/22826932/2c49bb9e-efe9-11e6-8a65-6bd2e671a276.png)
![screenshot 2017-02-10 23 23 58](https://cloud.githubusercontent.com/assets/25685344/22826933/2c4e24ea-efe9-11e6-8800-20a937903781.png)

.

**Comment by jaboles** [comment]
1c60ec3
--
