### ISSUE TITLE
NSW TrainLink trains include time of departure on indicator

### ISSUE THREAD

**Issue by Petarkco** [jaboles/DVA5#12]
![img_20170202_091934](https://user-images.githubusercontent.com/25685344/29809622-4893431c-8ce0-11e7-8e15-a96eb1cc5643.jpg)

**Comment by MLVDau** [comment]
![img_20170516_164500](https://user-images.githubusercontent.com/25685344/29905059-a942ba74-8e4f-11e7-805c-329b102706a3.jpg)
Another photo for reference which also shows that the line used for vias is left blank where isn't one instead of the other elements moving to fill the space.

**Comment by jaboles** [comment]
I've corrected this and it will be in the next release.
