### ISSUE TITLE
Update PID Line Names/Colours

### ISSUE THREAD

**Issue by ctn88** [jaboles/DVA5#14]
The old T2 line has now split into T8 Airport and South and T2 Inner West and Leppington. After pulling the new timetable the PID cannot be displayed due to the software not recognising/working with the new line names/colours
[Sydney Trains Suburban Map 2018](http://www.sydneytrains.info/stations/pdf/suburban_map.pdf)

**Comment by jaboles** [comment]
Version 5.4 now uses TfNSW timetable data with up-to-date lines.
