### ISSUE TITLE
Indicator Design is outdated

### ISSUE THREAD

**Issue by kurisubrooks** [jaboles/DVA5#18]
The current Indicator design features many old design features that have since been changed.

- Platform No. and Departure Time are no longer orange, but black
- Text is no longer navy, but black (hex #000000)
- Label (8 cars, Limited stops) elements are no longer navy, but grey (hex #363938)
- Label terminology is out of date (8 carriages -> 8 cars)
- Label width is no longer a fixed size, but uses the width of the longest text element
- Portrait Label position is incorrect (from the right side to the bottom of the scroll list)
- Airport stations (Domestic, International) feature an Airplane icon next to their names in the station scroll list
- "via airport stations" features an Airplane icon next to their names in the station scroll list

Airplane icon svg;
```svg
<svg id="tfnsw_airplane" data-name="tfnsw_airplane" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500">
  <defs>
    <style> .cls-1 { fill-rule: evenodd; } </style>
  </defs>
  <path class="cls-1"
    d="M455.47,475.51,372.94,188.77a3.28,3.28,0,0,0-.88-1.76C437.14,118.17,500,37.09,500,13.57A13.07,13.07,0,0,0,496.06,4c-5.24-5.23-14-13.94-82.94,38.8a1272.58,1272.58,0,0,0-100.43,85.84c-.42-.42-1.3-.42-1.72-.88L24.53,45.38,2.68,67.19A9.34,9.34,0,0,0,0,74.6a11.25,11.25,0,0,0,4,7L215.32,227.15,119.67,337.39,51.11,323.88,31.49,343.46a9.37,9.37,0,0,0,2.13,14.82L105.24,394,141,465.46a9.39,9.39,0,0,0,1.71,2.64,10.2,10.2,0,0,0,5.24,2.64c3.07.41,6.13-.42,7.84-2.64l19.67-19.59-13.54-66.67c0-.46-.42-.88-.42-1.34l111.75-95.42L419.1,496c1.76,2.17,3.94,3.93,7,3.93a9.2,9.2,0,0,0,7.43-2.64l21.94-21.8Z" />
</svg>
```

I've included some images of the updated indicator design below;

<details>
  <summary>SPOILER (Click to show)</summary>
  
![img](https://user-images.githubusercontent.com/6291467/146296408-3d0d92ca-bc1e-4ec7-8126-dcac2479225b.jpg)
![@tsydneyrail_spotters 2021-09-19__132353](https://user-images.githubusercontent.com/6291467/146296532-410eccc6-6ebd-47f1-aed2-5492f77453c9.JPEG)
![@tsydneyrail_spotters 2021-09-19__132254](https://user-images.githubusercontent.com/6291467/146296537-eb47b6d9-b26b-4b4d-9ae5-5516038e2a4d.JPEG)
![@tsydneyrail_spotters 2021-09-19__131826](https://user-images.githubusercontent.com/6291467/146296566-ae4bcfb1-27ec-47ed-9c69-94852aa1ec5a.JPEG)
![@tsydneyrail_spotters 2021-09-19__131435](https://user-images.githubusercontent.com/6291467/146296576-aa04aca6-0b13-4d5d-a6a0-2857a4bd136f.JPEG)
![IMG_1890](https://user-images.githubusercontent.com/6291467/146296776-81e46c6b-228b-4e29-a990-f2dfdd25ef01.PNG)
![IMG_7130](https://user-images.githubusercontent.com/6291467/146296810-91a67c1c-2328-4ccd-b437-fe2c58852036.JPG)
![IMG_8009](https://user-images.githubusercontent.com/6291467/146296818-434cec00-7ea6-4d20-9132-8f2d033a0221.jpg)

Reference (current design) DVA5 indicator image;
![image](https://user-images.githubusercontent.com/6291467/146296051-1aa7434a-cb33-49cc-b03e-b5bcc4205f9f.png)
</details>

**Comment by jaboles** [comment]
Thank you for the detailed photos! I will have a look at implementing the new indicator appearance.

**Comment by jaboles** [comment]
Added the new indicator style which will be in the next release. Will do the occupancy indication in a future version.
