### ISSUE TITLE
No anti-aliasing for indicator text

### ISSUE THREAD

**Issue by MLVDau** [jaboles/DVA5#2]
Text on the indicators are not anti-aliased making text jagged.

![screenshot 2017-02-10 23 23 58](https://cloud.githubusercontent.com/assets/25685344/22827001/a780350e-efe9-11e6-8056-69e0e0a7916e.png)

**Comment by jaboles** [comment]
Need to do some more research on this and get back to you. The plasma screen code does enable the antialiasing settings but whether it actually has an effect seems to depend on the java version and underlying OS.

MacOS+Java 6 does has antialiasing in my testing.
MacOS+Java 8 does not -- see https://stackoverflow.com/questions/32557025/why-is-intellij-ideas-font-rendering-worse-with-jdk-1-8-vs-1-6
Windows seems not to, but maybe I haven't found the right setting yet.

**Comment by jaboles** [comment]
d74b4d1
