### ISSUE TITLE
V4-5 indicators do not show "Via ..." line

### ISSUE THREAD

**Issue by Petarkco** [jaboles/DVA5#22]
![image](https://user-images.githubusercontent.com/25685344/173175083-ee0de7c0-42b1-41ed-bb76-b19782d0ee14.png)
![image](https://user-images.githubusercontent.com/25685344/173175087-71d955fd-8797-41fa-8d8c-8805fd9a8189.png)

![image](https://user-images.githubusercontent.com/25685344/173175098-26b1d4b1-4184-4209-b684-fb6fb88baf93.png)

**Comment by jaboles** [comment]
https://github.com/jaboles/DVA5/commit/38898978ae31148ece65fd3880ab583b0d979701
