### ISSUE TITLE
Indicator Board announcements ending in "all stations to"

### ISSUE THREAD

**Issue by sudface** [jaboles/DVA5#27]
Hi, love your work!

There seems to be an issue with trains where their last sequence of stops is all stations.

In the Indicators menu when loading an all stations to Richmond train (eg. `Blacktown, Marayong, Quakers Hill, Schofields, Riverstone, Vineyard, Mulgrave, Windsor, Clarendon, East Richmond, Richmond`), the `all stations to Richmond` does not get processed properly. 

The app interprets it as `First stop Blacktown, ^then all stations to Richmond.` when in fact it should be `First stop Blacktown, and then, all stations to Richmond.` (Inflection clash + wrong audio files). This issue does not seem localised to Richmond trains as it occurs with Hornsby trains too, in the `Chatswood, Lindfield, Gordon, Pymble, Turramurra, Warrawee, Wahroonga, Waitara, Hornsby` sequence, and in Penrith trains in the  `Blacktown, Doonside, Rooty Hill, Mount Druitt, St Marys, Werrington, Kingswood, Penrith` sequence. 

However, in the Richmond and Penrith cases, when preceded with Seven Hills (eg. `Seven Hills, Blacktown, Doonside, Rooty Hill, Mount Druitt, St Marys, Werrington, Kingswood, Penrith`), it interprets it almost correctly, with `...Blacktown, and all stations to Richmond.` instead of `...Blacktown, and then, all stations to Richmond.`

Thanks!!

**Comment by jaboles** [comment]
Should be fixed in newest version. Thanks!

**Comment by sudface** [comment]
Awesome!
The railpage website seems to have been down for quite a while, is there a direct link we can use to the releases?

**Comment by jaboles** [comment]
You can start up the current version and it will ask to update.Otherwise, which OS are you using?Sent from my iPadOn 1 Nov 2023, at 8:31 pm, Sudarshan ***@***.***> wrote:﻿
Awesome!
The railpage website seems to have been down for quite a while, is there a direct link we can use to the releases?

**Comment by sudface** [comment]
I'm on Windows, thanks

**Comment by jaboles** [comment]
http://dvaupdate.blob.core.windows.net/5-5-15/DVA5Setup.exeSent from my iPadOn 1 Nov 2023, at 9:49 pm, Sudarshan ***@***.***> wrote:﻿
I'm on Windows, thanks



On Thu, Nov 2, 2023 at 3:41 PM Jonathan Boles ***@***.***>

wrote:
