### ISSUE TITLE
Target "AllSetups" does not exist in the project "DVA"

### ISSUE THREAD

**Issue by sebbthepleb** [jaboles/DVA5#28]
Following your build guide on githack, the following error occurs :
**Target "AllSetups" does not exist in the project "DVA"**
Running ant without a target delivers a .jar that presents a java exception when opened.
I am not very well-versed in java or compiling, so i am not too sure on what the problem could be, and this seemed like the most appropriate place to put it.

**Comment by jaboles** [comment]
Building one OS' build on another OS likely won't work anymore. Also the build instructions are outdated. 'AllSetups' target has been removed, you can try building the target for your computer's OS:
- ant BuildMacDmgs
- ant BuildWinSetup
- ant BuildLinuxDebs

**Comment by sebbthepleb** [comment]
"ant BuildWinSetup" outputs DVA.exe that presents "Failed to find or load ini file" when opened.

**Comment by jaboles** [comment]
That’s just the application binary… run DVA5Setup.exe to install the full program.
