### ISSUE TITLE
Download Link Broken!

### ISSUE THREAD

**Issue by OfficalCloud-Codes** [jaboles/DVA5#29]
The download link will not work!
Apparently it takes too long to load
![image](https://github.com/jaboles/DVA5/assets/108596132/8e4c1444-d517-45ba-a266-09dea2d472a5)

**Comment by m1namim** [comment]
railpage, where the download link goes to, is currently down because of a hardware failure. it's being fixed right now, but there's no ETA for when it'll be back. any updates will come from the railpage facebook at https://www.facebook.com/railpage/

**Comment by Harely-Tran** [comment]
Is there anywhere i can ind a per-compiled app?

**Comment by jaboles** [comment]
See project homepage for updated info.
