### ISSUE TITLE
Request: Allow indicator to be selected on station then platform basis

### ISSUE THREAD

**Issue by Petarkco** [jaboles/DVA5#3]
Instead of the current method of selection Line->Direction->Station with platform being manually selected can it be that you can instead select Station->Platform?

**Comment by jaboles** [comment]
Requires the working timetable (which has more detailed info about train movements, far more detail than the one scraped from sydneytrains.info), and probably some complicated logic to parse it, so not saying this will never happen but it is unlikely :-)

**Comment by jaboles** [comment]
Version 5.4 now uses GTFS data from TfNSW and allows selection by station then platform (and optionally route)
