### ISSUE TITLE
Crashed installing update now wont load

### ISSUE THREAD

**Issue by MistaMark78** [jaboles/DVA5#31]
Hello readers,

I went to use the program today & it began an update 5.5.15. The download only got so far installing .jar files then crashed. Now DVA5 wont load at all. 

I tried reverting to a windows restore point from last week that didn't help either. 

I am aware the Railpage site has been down for a while now. But I was able to use the internet archive wayback machine & get a link to download the setup.exe file again. 

I attempted to update again to 5.5.15 & again it crashed during install.

Thanks,

Mark

**Comment by jaboles** [comment]
- Can you try uninstalling it from Programs & Features, delete c:\Program Files\DVA, and then try reinstalling it
- What OS / version / processor

**Comment by MistaMark78** [comment]
I've uninstalled twice now as you've described & reinstalled version 5.5.14.

The same problem still occurs.

Windows 10 version 22h2 AMD Ryzen 3 3100 processor.

**Comment by Jdinger03** [comment]
Hi @MistaMark78, I'm facing the same issue. I couldn't find the archive link for 5.5.14, is there any way you could point me to it?

**Comment by jaboles** [comment]
There was an issue with 5.5.15 -- see #32.

Try the latest 5.5.16 I believe it should be fixed: https://github.com/jaboles/DVA5/releases/tag/5.5.16
