### ISSUE TITLE
"Failed to find or load ini file" on startup

### ISSUE THREAD

**Issue by Petarkco** [jaboles/DVA5#32]
I have just done a fresh install on Windows 11 (using the latest release) and getting an error when attempting to start DVA.
![image](https://github.com/jaboles/DVA5/assets/25685344/053d13c0-e34d-4f88-a082-d4068801ffec)
The icon also appears to be different for some reason:
![image](https://github.com/jaboles/DVA5/assets/25685344/d54b9809-cde7-4dad-a9ed-309c6f7b4ff7)

Windows 11 Pro 23H2 (22631.2715) x64

**Comment by Petarkco** [comment]
Just tried running the setup again, the error also happens when the setup is updating sound libraries.
![image](https://github.com/jaboles/DVA5/assets/25685344/f9398d5d-84bf-4c50-83a7-b30857540b22)

**Comment by dnels842** [comment]
Also experiencing the same issue.
Win 11 22H2 22621.2715

**Comment by jaboles** [comment]
Thanks for reporting. Looks like Resource Hacker changed its command line handling in some way. A new version should be out shortly (5.5.16) which should fix the issue.

**Comment by jaboles** [comment]
The build uses Resource Hacker to embed resources in the .exe's (the .ini file and replacement icon). That's why the icon was different, and the error about the missing .ini file appeared.
