### ISSUE TITLE
Low FPS station list sctrolling 

### ISSUE THREAD

**Issue by Petarkco** [jaboles/DVA5#34]
https://github.com/jaboles/DVA5/assets/25685344/1a8200b2-7b31-4b9f-a670-6a7dc82535e6

https://github.com/jaboles/DVA5/assets/25685344/68998107-e7ed-4ac3-85db-50f2ec3a6940

Windows 11 23H2 x64 
NVIDIA GeForce 3080 Ti

**Comment by jaboles** [comment]
Hello, could you check the CPU usage of the app in Task Manager while the list is scrolling, also let me know how many cores the machine has?

**Comment by Petarkco** [comment]
![image](https://github.com/jaboles/DVA5/assets/25685344/f2608f05-0877-4962-92ee-05ebe3b66ddf)
![image](https://github.com/jaboles/DVA5/assets/25685344/06a0ab47-bcd6-4d31-8c26-2f842497aa47)

**Comment by jaboles** [comment]
Should be fixed in next version. Thanks for reporting!
