### ISSUE TITLE
Bug: TRANSLUCENT translucency is not supported.

### ISSUE THREAD

**Issue by SamLeatherdale** [jaboles/DVA5#35]
I'm unable to open this app under Ubuntu 22.04.3 LTS (x86_64), running Cinnamon or KDE Plasma desktop environment.

It works fine under the LXQt desktop environment.

I get the following error on startup:

```
java.lang.UnsupportedOperationException: TRANSLUCENT translucency is not supported.
	at java.desktop/java.awt.Window.setOpacity(Window.java:3680)
	at java.desktop/java.awt.Dialog.setOpacity(Dialog.java:1312)
	at jb.common.ui.WindowFader.fadeIn(WindowFader.java:26)
	at jb.dvacommon.ui.LoadWindow.show(LoadWindow.java:151)
	at jb.dvacommon.DVA.runApp(DVA.java:74)
	at jb.dvacommon.DVA.main(DVA.java:310)
```

Interestingly enough I still hear the startup sound "DVA 5" but no window appears, assumedly due to the error above.

I found [this StackOverflow issue](https://stackoverflow.com/questions/51145931/how-to-support-jframe-transparency-on-linux) which can help to check whether transparency is supported on a given platform.

Testing the above out on my machine, I get:
```
isUniformTranslucencySupported: false
isPerPixelTranslucencySupported: true
isShapedWindowSupported: true
```

**Comment by jaboles** [comment]
Thanks for reporting! Should be fixed in new version.
