### ISSUE TITLE
DVA 5 not having the default sound libraries

### ISSUE THREAD

**Issue by BlueARL44** [jaboles/DVA5#38]
I downloaded the DVA5 SETUP.exe as I operate in Windows. There is very few videos online regarding this app, but all of them seem to have all the announcers already in place in the voice libraries, whereas mine simply is none. 
![Screenshot (117)](https://github.com/jaboles/DVA5/assets/166122235/60bcfb8d-232e-4628-a907-9a45d34c307e)
Is there a way to solve this?

**Comment by Super-McTea** [comment]
I have the same issue unfortunately

**Comment by InvraNet** [comment]
Having issue too, I built the app myself to be sure, nothing so far.

**Comment by InvraNet** [comment]
Okay I found the fix. Please download the "Sounds" folder as a zip. Unzip it. Move all folders into `%localappdata%\DVA`

Your DVA directory should look a little like:
![Screenshot 2024-04-15 221050](https://github.com/jaboles/DVA5/assets/109136291/c487533d-0eb1-428a-bbe1-007033e4a027)

**Comment by NathanGP846** [comment]
How I Can Unzip It

**Comment by InvraNet** [comment]
> How Can I Unzip It

You should be able to just double-click then Windows will inflate it. If that does not work, then you can try to install [7Zip-FM](https://www.7-zip.org/download.html) then right-click then there should be in your right-click context menu ``Extract Here...``



> One problem with this - some of the longer file names will not transfer over, Windows claims that the path is too long.

That is seems to be that NTFS issue, you can change the "Directory Path Length"  via [This](https://www.backupery.com/how-to-enable-ntfs-long-paths-in-windows/) if you do this Window's HK(LM,LU) is CaSe SeNsItIvE, meaning if it tried to search for ``Key`` but you have ``key``: ``key`` will not be recognized as ``Key`` as it is theoretically a completely different file. Some apps are encompassed to not have this issue, windows explorer, and file system tables do **NOT** have this for reasons like if you have a duplicate file it will know which one to pick.

There is another way with [this link](https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing). 
**This will only work if you are on Windows 8/8.1/10/11 Professional**. The ``Regedit.msc`` is the **only** way on Windows 8/8.1/10/11 Home users.

**Comment by NathanGP846** [comment]
Ok

**Comment by NathanGP846** [comment]
InvraNet I Cant Find Enable NTFS Long Paths

**Comment by NathanGP846** [comment]
OMG IT WORK!!
TY INRVANET FOR HELP ME!!! 
OMG IM SO HAPPY!!

**Comment by NathanGP846** [comment]
I WAS ABOUT TO CRY

**Comment by InvraNet** [comment]
You are welcome.

**Comment by NathanGP846** [comment]
:)

**Comment by jaboles** [comment]
Sorry about this. The sound libraries should be downloaded during the running of the installer but it looks like this isn’t happening. Possibly due to expiry of the code signing certificate which I’ve posted about in another issue. I’ll think about possible solutions.

**Comment by NathanGP846** [comment]
It Ok :)

**Comment by NathanGP846** [comment]
I Got It Back!

**Comment by InvraNet** [comment]
> Sorry about this. The sound libraries should be downloaded during the running of the installer but it looks like this isn’t happening. Possibly due to expiry of the code signing certificate which I’ve posted about in another issue. I’ll think about possible solutions.

If you create a proper installer and get it to pull all of the data into its desired places it should work. Also where would the equivalent of %localappdata%\DVA be on linux?

**Comment by GaRoMe119** [comment]
Curious about a fix for Mac as well! Thanks 👍

**Comment by jaboles** [comment]
Looks like this issue is happening when making HTTPS requests to Azure but I have no idea why./

     [exec] javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
     [exec] javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
     [exec] 	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:956)
     [exec] 	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
     [exec] 	at jb.common.FileUtilities.readFromUrl(FileUtilities.java:77)
     [exec] 	at jb.dvacommon.WAzureUpdater.getLatestVersion(WAzureUpdater.java:54)
     [exec] 	at jb.dvacommon.Updater.lambda$updateAvailable$1(Updater.java:44)
     [exec] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
     [exec] 	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
     [exec] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
     [exec] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
     [exec] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
     [exec] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
     [exec] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
     [exec] 	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
     [exec] 	at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:698)
     [exec] 	at jb.dvacommon.Updater.updateAvailable(Updater.java:47)
     [exec] 	at jb.dvacommon.ui.DVAShell.lambda$setVisible$4(DVAShell.java:153)
     [exec] 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by jaboles** [comment]
I found the issue and there will a new version out shortly that fixes it.

**Comment by jaboles** [comment]
Fixed in 5.5.19. Note that you will need to uninstall/delete the old version and then install the newer version manually.
