### ISSUE TITLE
V4 indicator shows 0 min instead of time text dissapearing

### ISSUE THREAD

**Issue by MLVDau** [jaboles/DVA5#4]
Currently the V4 indicator shows "0 min" when the train is due, on the real indicators the time/departs text simply disappears.

![screenshot 2017-02-10 23 41 54](https://cloud.githubusercontent.com/assets/25685344/22827215/bbb630cc-efea-11e6-8868-b0e3358cd4db.png)

![screenshot 2017-02-10 23 46 30](https://cloud.githubusercontent.com/assets/25685344/22827330/5a3295ba-efeb-11e6-9084-19d3cdd31322.png)

**Comment by jaboles** [comment]
93b8344
