### ISSUE TITLE
V4 Indicator: Intercity indicator differences

### ISSUE THREAD

**Issue by MLVDau** [jaboles/DVA5#6]
Currently:
![screenshot 2017-02-10 23 51 25](https://cloud.githubusercontent.com/assets/25685344/22827416/eb2ec23c-efeb-11e6-9c64-0ccd7bc37c82.png)

Real:
![screenshot 2017-02-10 23 52 59](https://cloud.githubusercontent.com/assets/25685344/22827446/1427b568-efec-11e6-8dd6-af4405925b38.png)
Note that all platform indicators show the T symbol.

**Comment by jaboles** [comment]
cb24b5d
